theme: jekyll-theme-hacker
title: Ashish D'Souza (computer-geek64)
description: Programmer, developer, penetration tester, stock investor, Mensa member, and Delaware SkillsUSA President. Languages: Java, Python, Bash, Ruby, AWK, HTML/CSS, JS, PHP, Arduino.
