theme: jekyll-theme-hacker
title: computer-geek64
description: Programmer, developer, penetration tester, stock investor, Mensa member. Languages: Java, Python, Bash, Ruby, AWK, HTML/CSS, JS, PHP, Arduino.
